/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package z.pkg80;

import Archivos.Comandos;
import java.util.HashMap;
import java.util.LinkedList;
import java.util.List;
import javax.swing.JOptionPane;
import sun.tools.jconsole.Messages;

/**
 *
 * @author Ricardo
 */
public class Ejecucion extends javax.swing.JFrame {

    
    
    public List<Comandos> comandos = new LinkedList<>();
    public String direccion_carga;
    public int[][] memoria = new int[1000][16];
    
    public Ejecucion() {
        initComponents();
        this.A_value.setText("0000");
        this.B_value.setText("0000");
        this.C_value.setText("0000");
        this.D_value.setText("0000");
        this.E_value.setText("0000");
        this.F_value.setText("0000");
        this.H_value.setText("0000");
        this.L_value.setText("0000");
        this.A_value1.setText("0000");
        this.B_value1.setText("0000");
        this.C_value1.setText("0000");
        this.D_value1.setText("0000");
        this.E_value1.setText("0000");
        this.F_value1.setText("0000");
        this.H_value1.setText("0000");
        this.L_value1.setText("0000");
        this.PC_value.setText("0000");
        this.SP_value.setText("0000");
        this.IX_value.setText("0000");
        this.IY_value.setText("0000");
        this.I_value.setText("0000");
        this.R_value.setText("0000");
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">                          
    private void initComponents() {

        jScrollPane2 = new javax.swing.JScrollPane();
        jTextArea1 = new javax.swing.JTextArea();
        Panel_Registros = new javax.swing.JPanel();
        A = new javax.swing.JLabel();
        Titulo_Registros = new javax.swing.JLabel();
        B = new javax.swing.JLabel();
        F = new javax.swing.JLabel();
        C = new javax.swing.JLabel();
        D = new javax.swing.JLabel();
        E = new javax.swing.JLabel();
        H = new javax.swing.JLabel();
        L = new javax.swing.JLabel();
        IY = new javax.swing.JLabel();
        IX = new javax.swing.JLabel();
        SP = new javax.swing.JLabel();
        I = new javax.swing.JLabel();
        R = new javax.swing.JLabel();
        FLAGS = new javax.swing.JLabel();
        PC = new javax.swing.JLabel();
        B_value = new javax.swing.JLabel();
        A_value = new javax.swing.JLabel();
        F_value = new javax.swing.JLabel();
        D_value = new javax.swing.JLabel();
        C_value = new javax.swing.JLabel();
        E_value = new javax.swing.JLabel();
        L_value = new javax.swing.JLabel();
        H_value = new javax.swing.JLabel();
        F1 = new javax.swing.JLabel();
        F_value1 = new javax.swing.JLabel();
        A1 = new javax.swing.JLabel();
        A_value1 = new javax.swing.JLabel();
        B1 = new javax.swing.JLabel();
        B_value1 = new javax.swing.JLabel();
        C1 = new javax.swing.JLabel();
        C_value1 = new javax.swing.JLabel();
        D1 = new javax.swing.JLabel();
        D_value1 = new javax.swing.JLabel();
        E1 = new javax.swing.JLabel();
        E_value1 = new javax.swing.JLabel();
        H1 = new javax.swing.JLabel();
        H_value1 = new javax.swing.JLabel();
        L1 = new javax.swing.JLabel();
        L_value1 = new javax.swing.JLabel();
        S_F = new javax.swing.JLabel();
        Z_F = new javax.swing.JLabel();
        H_F = new javax.swing.JLabel();
        P_F = new javax.swing.JLabel();
        N_F = new javax.swing.JLabel();
        C_F = new javax.swing.JLabel();
        SF_value = new javax.swing.JLabel();
        ZF_value = new javax.swing.JLabel();
        Tercer_0 = new javax.swing.JLabel();
        HF_value = new javax.swing.JLabel();
        Quinto_0 = new javax.swing.JLabel();
        PF_value = new javax.swing.JLabel();
        NF_value = new javax.swing.JLabel();
        CF_value = new javax.swing.JLabel();
        IX_value = new javax.swing.JLabel();
        PC_value = new javax.swing.JLabel();
        IY_value = new javax.swing.JLabel();
        I_value = new javax.swing.JLabel();
        SP_value = new javax.swing.JLabel();
        R_value = new javax.swing.JLabel();
        Panel_Comandos = new javax.swing.JPanel();
        Titulo_Comandos = new javax.swing.JLabel();
        Volver = new javax.swing.JButton();
        Libre = new javax.swing.JButton();
        Paso = new javax.swing.JButton();
        Titulo_Inicio = new javax.swing.JLabel();
        Titulo_Set_Registro = new javax.swing.JLabel();
        Text_Set_value = new javax.swing.JTextField();
        Text_Set_Registro = new javax.swing.JTextField();
        Set_Registro = new javax.swing.JLabel();
        Set_Registro_value = new javax.swing.JLabel();
        Panel_Desensamble = new javax.swing.JPanel();
        Titulo_Entradas = new javax.swing.JLabel();
        jScrollPane1 = new javax.swing.JScrollPane();
        TextArea = new javax.swing.JTextArea();
        Panel_Puertos = new javax.swing.JPanel();
        Titulo_Salidas = new javax.swing.JLabel();
        Titulo_Entradas1 = new javax.swing.JLabel();
        Panel_Pila = new javax.swing.JPanel();
        Titulo_Pila = new javax.swing.JLabel();
        jScrollPane3 = new javax.swing.JScrollPane();
        NumerosPila = new javax.swing.JTextPane();

        jTextArea1.setColumns(20);
        jTextArea1.setRows(5);
        jScrollPane2.setViewportView(jTextArea1);

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        Panel_Registros.setBackground(new java.awt.Color(204, 204, 255));

        A.setFont(new java.awt.Font("Sylfaen", 1, 15)); // NOI18N
        A.setText("A");

        Titulo_Registros.setFont(new java.awt.Font("Sylfaen", 1, 15)); // NOI18N
        Titulo_Registros.setText("Registros Internos");

        B.setFont(new java.awt.Font("Sylfaen", 1, 15)); // NOI18N
        B.setText("B");

        F.setFont(new java.awt.Font("Sylfaen", 1, 15)); // NOI18N
        F.setText("F");
        F.setToolTipText("");

        C.setFont(new java.awt.Font("Sylfaen", 1, 15)); // NOI18N
        C.setText("C");

        D.setFont(new java.awt.Font("Sylfaen", 1, 15)); // NOI18N
        D.setText("D");

        E.setFont(new java.awt.Font("Sylfaen", 1, 15)); // NOI18N
        E.setText("E");

        H.setFont(new java.awt.Font("Sylfaen", 1, 15)); // NOI18N
        H.setText("H");

        L.setFont(new java.awt.Font("Sylfaen", 1, 15)); // NOI18N
        L.setText("L");

        IY.setFont(new java.awt.Font("Sylfaen", 1, 15)); // NOI18N
        IY.setText("IY");

        IX.setFont(new java.awt.Font("Sylfaen", 1, 15)); // NOI18N
        IX.setText("IX");

        SP.setFont(new java.awt.Font("Sylfaen", 1, 15)); // NOI18N
        SP.setText("SP");
        SP.setToolTipText("");

        I.setFont(new java.awt.Font("Sylfaen", 1, 15)); // NOI18N
        I.setText("I");

        R.setFont(new java.awt.Font("Sylfaen", 1, 15)); // NOI18N
        R.setText("R");

        FLAGS.setFont(new java.awt.Font("Sylfaen", 1, 15)); // NOI18N
        FLAGS.setText("FLAGS");

        PC.setFont(new java.awt.Font("Sylfaen", 1, 15)); // NOI18N
        PC.setText("PC");

        B_value.setFont(new java.awt.Font("Sylfaen", 1, 15)); // NOI18N
        B_value.setText("B_value");

        A_value.setFont(new java.awt.Font("Sylfaen", 1, 15)); // NOI18N
        A_value.setText("A_value");

        F_value.setFont(new java.awt.Font("Sylfaen", 1, 15)); // NOI18N
        F_value.setText("F_value");

        D_value.setFont(new java.awt.Font("Sylfaen", 1, 15)); // NOI18N
        D_value.setText("D_value");

        C_value.setFont(new java.awt.Font("Sylfaen", 1, 15)); // NOI18N
        C_value.setText("C_value");

        E_value.setFont(new java.awt.Font("Sylfaen", 1, 15)); // NOI18N
        E_value.setText("E_value");

        L_value.setFont(new java.awt.Font("Sylfaen", 1, 15)); // NOI18N
        L_value.setText("L_value");

        H_value.setFont(new java.awt.Font("Sylfaen", 1, 15)); // NOI18N
        H_value.setText("H_value");

        F1.setFont(new java.awt.Font("Sylfaen", 1, 15)); // NOI18N
        F1.setText("F'");
        F1.setToolTipText("");

        F_value1.setFont(new java.awt.Font("Sylfaen", 1, 15)); // NOI18N
        F_value1.setText("F'_value");

        A1.setFont(new java.awt.Font("Sylfaen", 1, 15)); // NOI18N
        A1.setText("A'");

        A_value1.setFont(new java.awt.Font("Sylfaen", 1, 15)); // NOI18N
        A_value1.setText("A'_value");

        B1.setFont(new java.awt.Font("Sylfaen", 1, 15)); // NOI18N
        B1.setText("B'");

        B_value1.setFont(new java.awt.Font("Sylfaen", 1, 15)); // NOI18N
        B_value1.setText("B'_value");

        C1.setFont(new java.awt.Font("Sylfaen", 1, 15)); // NOI18N
        C1.setText("C'");

        C_value1.setFont(new java.awt.Font("Sylfaen", 1, 15)); // NOI18N
        C_value1.setText("C'_value");

        D1.setFont(new java.awt.Font("Sylfaen", 1, 15)); // NOI18N
        D1.setText("D'");

        D_value1.setFont(new java.awt.Font("Sylfaen", 1, 15)); // NOI18N
        D_value1.setText("D'_value");

        E1.setFont(new java.awt.Font("Sylfaen", 1, 15)); // NOI18N
        E1.setText("E'");

        E_value1.setFont(new java.awt.Font("Sylfaen", 1, 15)); // NOI18N
        E_value1.setText("E'_value");

        H1.setFont(new java.awt.Font("Sylfaen", 1, 15)); // NOI18N
        H1.setText("H'");

        H_value1.setFont(new java.awt.Font("Sylfaen", 1, 15)); // NOI18N
        H_value1.setText("H'_value");

        L1.setFont(new java.awt.Font("Sylfaen", 1, 15)); // NOI18N
        L1.setText("L'");

        L_value1.setFont(new java.awt.Font("Sylfaen", 1, 15)); // NOI18N
        L_value1.setText("L'_value");

        S_F.setFont(new java.awt.Font("Sylfaen", 1, 15)); // NOI18N
        S_F.setText("S");

        Z_F.setFont(new java.awt.Font("Sylfaen", 1, 15)); // NOI18N
        Z_F.setText("Z");

        H_F.setFont(new java.awt.Font("Sylfaen", 1, 15)); // NOI18N
        H_F.setText("H");

        P_F.setFont(new java.awt.Font("Sylfaen", 1, 15)); // NOI18N
        P_F.setText("P");

        N_F.setFont(new java.awt.Font("Sylfaen", 1, 15)); // NOI18N
        N_F.setText("N");

        C_F.setFont(new java.awt.Font("Sylfaen", 1, 15)); // NOI18N
        C_F.setText("C");

        SF_value.setFont(new java.awt.Font("Sylfaen", 1, 15)); // NOI18N
        SF_value.setText("0");

        ZF_value.setFont(new java.awt.Font("Sylfaen", 1, 15)); // NOI18N
        ZF_value.setText("0");

        Tercer_0.setFont(new java.awt.Font("Sylfaen", 1, 15)); // NOI18N
        Tercer_0.setText("0");

        HF_value.setFont(new java.awt.Font("Sylfaen", 1, 15)); // NOI18N
        HF_value.setText("0");

        Quinto_0.setFont(new java.awt.Font("Sylfaen", 1, 15)); // NOI18N
        Quinto_0.setText("0");

        PF_value.setFont(new java.awt.Font("Sylfaen", 1, 15)); // NOI18N
        PF_value.setText("0");

        NF_value.setFont(new java.awt.Font("Sylfaen", 1, 15)); // NOI18N
        NF_value.setText("0");

        CF_value.setFont(new java.awt.Font("Sylfaen", 1, 15)); // NOI18N
        CF_value.setText("0");

        IX_value.setFont(new java.awt.Font("Sylfaen", 1, 15)); // NOI18N
        IX_value.setText("IX_value");

        PC_value.setFont(new java.awt.Font("Sylfaen", 1, 15)); // NOI18N
        PC_value.setText("PC_value");

        IY_value.setFont(new java.awt.Font("Sylfaen", 1, 15)); // NOI18N
        IY_value.setText("IY_value");

        I_value.setFont(new java.awt.Font("Sylfaen", 1, 15)); // NOI18N
        I_value.setText("I_value");

        SP_value.setFont(new java.awt.Font("Sylfaen", 1, 15)); // NOI18N
        SP_value.setText("SP_value");

        R_value.setFont(new java.awt.Font("Sylfaen", 1, 15)); // NOI18N
        R_value.setText("R_value");

        javax.swing.GroupLayout Panel_RegistrosLayout = new javax.swing.GroupLayout(Panel_Registros);
        Panel_Registros.setLayout(Panel_RegistrosLayout);
        Panel_RegistrosLayout.setHorizontalGroup(
            Panel_RegistrosLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(Panel_RegistrosLayout.createSequentialGroup()
                .addGroup(Panel_RegistrosLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(Panel_RegistrosLayout.createSequentialGroup()
                        .addGroup(Panel_RegistrosLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(Panel_RegistrosLayout.createSequentialGroup()
                                .addGap(79, 79, 79)
                                .addComponent(S_F))
                            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, Panel_RegistrosLayout.createSequentialGroup()
                                .addContainerGap()
                                .addComponent(FLAGS)
                                .addGap(18, 18, 18)
                                .addComponent(SF_value, javax.swing.GroupLayout.PREFERRED_SIZE, 11, javax.swing.GroupLayout.PREFERRED_SIZE)))
                        .addGroup(Panel_RegistrosLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(Panel_RegistrosLayout.createSequentialGroup()
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addComponent(Z_F))
                            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, Panel_RegistrosLayout.createSequentialGroup()
                                .addGap(3, 3, 3)
                                .addComponent(ZF_value, javax.swing.GroupLayout.PREFERRED_SIZE, 12, javax.swing.GroupLayout.PREFERRED_SIZE)))
                        .addGap(2, 2, 2)
                        .addComponent(Tercer_0, javax.swing.GroupLayout.PREFERRED_SIZE, 8, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addGroup(Panel_RegistrosLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                            .addGroup(Panel_RegistrosLayout.createSequentialGroup()
                                .addComponent(H_F)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                .addComponent(P_F)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addComponent(N_F)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addComponent(C_F))
                            .addGroup(Panel_RegistrosLayout.createSequentialGroup()
                                .addComponent(HF_value)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addComponent(Quinto_0)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addComponent(PF_value)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addComponent(NF_value)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addComponent(CF_value))))
                    .addGroup(Panel_RegistrosLayout.createSequentialGroup()
                        .addGroup(Panel_RegistrosLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(Panel_RegistrosLayout.createSequentialGroup()
                                .addGap(37, 37, 37)
                                .addGroup(Panel_RegistrosLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addGroup(Panel_RegistrosLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                                        .addGroup(Panel_RegistrosLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                            .addGroup(Panel_RegistrosLayout.createSequentialGroup()
                                                .addComponent(F)
                                                .addGap(18, 18, 18)
                                                .addComponent(F_value, javax.swing.GroupLayout.PREFERRED_SIZE, 78, javax.swing.GroupLayout.PREFERRED_SIZE))
                                            .addGroup(Panel_RegistrosLayout.createSequentialGroup()
                                                .addComponent(B)
                                                .addGap(18, 18, 18)
                                                .addComponent(B_value, javax.swing.GroupLayout.PREFERRED_SIZE, 78, javax.swing.GroupLayout.PREFERRED_SIZE))
                                            .addGroup(Panel_RegistrosLayout.createSequentialGroup()
                                                .addGap(1, 1, 1)
                                                .addComponent(A)
                                                .addGap(18, 18, 18)
                                                .addComponent(A_value, javax.swing.GroupLayout.PREFERRED_SIZE, 74, javax.swing.GroupLayout.PREFERRED_SIZE)))
                                        .addGroup(Panel_RegistrosLayout.createSequentialGroup()
                                            .addComponent(C)
                                            .addGap(18, 18, 18)
                                            .addComponent(C_value, javax.swing.GroupLayout.PREFERRED_SIZE, 78, javax.swing.GroupLayout.PREFERRED_SIZE)))
                                    .addGroup(Panel_RegistrosLayout.createSequentialGroup()
                                        .addComponent(D)
                                        .addGap(18, 18, 18)
                                        .addComponent(D_value, javax.swing.GroupLayout.PREFERRED_SIZE, 78, javax.swing.GroupLayout.PREFERRED_SIZE))
                                    .addGroup(Panel_RegistrosLayout.createSequentialGroup()
                                        .addComponent(E)
                                        .addGap(18, 18, 18)
                                        .addComponent(E_value, javax.swing.GroupLayout.PREFERRED_SIZE, 78, javax.swing.GroupLayout.PREFERRED_SIZE))
                                    .addGroup(Panel_RegistrosLayout.createSequentialGroup()
                                        .addGroup(Panel_RegistrosLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                            .addComponent(H)
                                            .addComponent(L))
                                        .addGap(18, 18, 18)
                                        .addGroup(Panel_RegistrosLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                            .addComponent(L_value, javax.swing.GroupLayout.PREFERRED_SIZE, 78, javax.swing.GroupLayout.PREFERRED_SIZE)
                                            .addComponent(H_value, javax.swing.GroupLayout.PREFERRED_SIZE, 78, javax.swing.GroupLayout.PREFERRED_SIZE)))))
                            .addGroup(Panel_RegistrosLayout.createSequentialGroup()
                                .addContainerGap()
                                .addComponent(PC)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                                .addComponent(PC_value, javax.swing.GroupLayout.PREFERRED_SIZE, 78, javax.swing.GroupLayout.PREFERRED_SIZE)))
                        .addGroup(Panel_RegistrosLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(Panel_RegistrosLayout.createSequentialGroup()
                                .addGap(90, 90, 90)
                                .addGroup(Panel_RegistrosLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addGroup(Panel_RegistrosLayout.createSequentialGroup()
                                        .addComponent(L1)
                                        .addGap(18, 18, 18)
                                        .addComponent(L_value1, javax.swing.GroupLayout.PREFERRED_SIZE, 78, javax.swing.GroupLayout.PREFERRED_SIZE))
                                    .addGroup(Panel_RegistrosLayout.createSequentialGroup()
                                        .addComponent(H1)
                                        .addGap(18, 18, 18)
                                        .addComponent(H_value1, javax.swing.GroupLayout.PREFERRED_SIZE, 78, javax.swing.GroupLayout.PREFERRED_SIZE))
                                    .addGroup(Panel_RegistrosLayout.createSequentialGroup()
                                        .addComponent(E1)
                                        .addGap(18, 18, 18)
                                        .addComponent(E_value1, javax.swing.GroupLayout.PREFERRED_SIZE, 78, javax.swing.GroupLayout.PREFERRED_SIZE))
                                    .addGroup(Panel_RegistrosLayout.createSequentialGroup()
                                        .addComponent(D1)
                                        .addGap(18, 18, 18)
                                        .addComponent(D_value1, javax.swing.GroupLayout.PREFERRED_SIZE, 78, javax.swing.GroupLayout.PREFERRED_SIZE))
                                    .addGroup(Panel_RegistrosLayout.createSequentialGroup()
                                        .addComponent(A1)
                                        .addGap(18, 18, 18)
                                        .addComponent(A_value1, javax.swing.GroupLayout.PREFERRED_SIZE, 74, javax.swing.GroupLayout.PREFERRED_SIZE))
                                    .addGroup(Panel_RegistrosLayout.createSequentialGroup()
                                        .addComponent(F1)
                                        .addGap(18, 18, 18)
                                        .addComponent(F_value1, javax.swing.GroupLayout.PREFERRED_SIZE, 78, javax.swing.GroupLayout.PREFERRED_SIZE))
                                    .addGroup(Panel_RegistrosLayout.createSequentialGroup()
                                        .addComponent(B1)
                                        .addGap(18, 18, 18)
                                        .addComponent(B_value1, javax.swing.GroupLayout.PREFERRED_SIZE, 78, javax.swing.GroupLayout.PREFERRED_SIZE))
                                    .addGroup(Panel_RegistrosLayout.createSequentialGroup()
                                        .addComponent(C1)
                                        .addGap(18, 18, 18)
                                        .addComponent(C_value1, javax.swing.GroupLayout.PREFERRED_SIZE, 78, javax.swing.GroupLayout.PREFERRED_SIZE))))
                            .addGroup(Panel_RegistrosLayout.createSequentialGroup()
                                .addGap(93, 93, 93)
                                .addGroup(Panel_RegistrosLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addGroup(Panel_RegistrosLayout.createSequentialGroup()
                                        .addComponent(IX)
                                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                                        .addComponent(IX_value, javax.swing.GroupLayout.PREFERRED_SIZE, 78, javax.swing.GroupLayout.PREFERRED_SIZE))
                                    .addGroup(Panel_RegistrosLayout.createSequentialGroup()
                                        .addGroup(Panel_RegistrosLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                            .addComponent(IY)
                                            .addComponent(SP))
                                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                                        .addGroup(Panel_RegistrosLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                            .addComponent(IY_value, javax.swing.GroupLayout.PREFERRED_SIZE, 78, javax.swing.GroupLayout.PREFERRED_SIZE)
                                            .addComponent(SP_value, javax.swing.GroupLayout.PREFERRED_SIZE, 78, javax.swing.GroupLayout.PREFERRED_SIZE))
                                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                        .addGroup(Panel_RegistrosLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                            .addComponent(R)
                                            .addComponent(I)))))))
                    .addGroup(Panel_RegistrosLayout.createSequentialGroup()
                        .addContainerGap()
                        .addComponent(Titulo_Registros)))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(Panel_RegistrosLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(I_value, javax.swing.GroupLayout.PREFERRED_SIZE, 78, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(R_value, javax.swing.GroupLayout.PREFERRED_SIZE, 78, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addContainerGap())
        );
        Panel_RegistrosLayout.setVerticalGroup(
            Panel_RegistrosLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(Panel_RegistrosLayout.createSequentialGroup()
                .addContainerGap()
                .addComponent(Titulo_Registros)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(Panel_RegistrosLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(F)
                    .addComponent(F_value)
                    .addComponent(F1)
                    .addComponent(F_value1))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(Panel_RegistrosLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(A)
                    .addComponent(A_value)
                    .addComponent(A1)
                    .addComponent(A_value1))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(Panel_RegistrosLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(B_value)
                    .addComponent(B)
                    .addComponent(B1)
                    .addComponent(B_value1))
                .addGap(5, 5, 5)
                .addGroup(Panel_RegistrosLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(C)
                    .addComponent(C_value)
                    .addComponent(C1)
                    .addComponent(C_value1))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(Panel_RegistrosLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(D)
                    .addComponent(D_value)
                    .addComponent(D1)
                    .addComponent(D_value1))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(Panel_RegistrosLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(E)
                    .addComponent(E1)
                    .addComponent(E_value1)
                    .addComponent(E_value))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(Panel_RegistrosLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(H)
                    .addComponent(H1)
                    .addComponent(H_value1)
                    .addComponent(H_value))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(Panel_RegistrosLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(L)
                    .addComponent(L_value)
                    .addComponent(L1)
                    .addComponent(L_value1))
                .addGroup(Panel_RegistrosLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(Panel_RegistrosLayout.createSequentialGroup()
                        .addGap(0, 8, Short.MAX_VALUE)
                        .addGroup(Panel_RegistrosLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(FLAGS)
                            .addComponent(SF_value)
                            .addComponent(ZF_value)
                            .addComponent(Tercer_0)
                            .addComponent(HF_value)
                            .addComponent(Quinto_0)
                            .addComponent(PF_value)
                            .addComponent(NF_value)
                            .addComponent(CF_value))
                        .addGap(1, 1, 1)
                        .addGroup(Panel_RegistrosLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(S_F)
                            .addComponent(Z_F)
                            .addComponent(H_F)
                            .addComponent(P_F)
                            .addComponent(N_F)
                            .addComponent(C_F)
                            .addComponent(IY)
                            .addComponent(IY_value)
                            .addComponent(I)
                            .addComponent(I_value))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addGroup(Panel_RegistrosLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(PC)
                            .addComponent(SP)
                            .addComponent(SP_value)
                            .addComponent(PC_value)
                            .addComponent(R)
                            .addComponent(R_value)))
                    .addGroup(Panel_RegistrosLayout.createSequentialGroup()
                        .addGroup(Panel_RegistrosLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(IX)
                            .addComponent(IX_value))
                        .addGap(0, 0, Short.MAX_VALUE)))
                .addContainerGap())
        );

        Panel_Comandos.setBackground(new java.awt.Color(204, 51, 255));

        Titulo_Comandos.setFont(new java.awt.Font("Sylfaen", 1, 15)); // NOI18N
        Titulo_Comandos.setText("Comandos");

        Volver.setBackground(new java.awt.Color(153, 153, 153));
        Volver.setFont(new java.awt.Font("Sylfaen", 1, 15)); // NOI18N
        Volver.setText("Volver");
        Volver.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                Button_Volver(evt);
            }
        });

        Libre.setBackground(new java.awt.Color(153, 153, 153));
        Libre.setFont(new java.awt.Font("Sylfaen", 1, 15)); // NOI18N
        Libre.setText("Libre");
        Libre.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                Button_Libre(evt);
            }
        });

        Paso.setBackground(new java.awt.Color(153, 153, 153));
        Paso.setFont(new java.awt.Font("Sylfaen", 1, 15)); // NOI18N
        Paso.setText("Paso a Paso");
        Paso.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                Button_Paso(evt);
            }
        });

        Titulo_Inicio.setFont(new java.awt.Font("Sylfaen", 1, 15)); // NOI18N
        Titulo_Inicio.setText("Forma de Ejecucion");

        Titulo_Set_Registro.setFont(new java.awt.Font("Sylfaen", 1, 15)); // NOI18N
        Titulo_Set_Registro.setText("Cambiar valor Registro");

        Text_Set_value.setFont(new java.awt.Font("Sylfaen", 0, 20)); // NOI18N

        Text_Set_Registro.setFont(new java.awt.Font("Sylfaen", 0, 20)); // NOI18N

        Set_Registro.setFont(new java.awt.Font("Sylfaen", 1, 15)); // NOI18N
        Set_Registro.setText("Registro");

        Set_Registro_value.setFont(new java.awt.Font("Sylfaen", 1, 15)); // NOI18N
        Set_Registro_value.setText("Valor");

        javax.swing.GroupLayout Panel_ComandosLayout = new javax.swing.GroupLayout(Panel_Comandos);
        Panel_Comandos.setLayout(Panel_ComandosLayout);
        Panel_ComandosLayout.setHorizontalGroup(
            Panel_ComandosLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(Panel_ComandosLayout.createSequentialGroup()
                .addGap(23, 23, 23)
                .addGroup(Panel_ComandosLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(Titulo_Comandos)
                    .addGroup(Panel_ComandosLayout.createSequentialGroup()
                        .addGap(21, 21, 21)
                        .addComponent(Libre)))
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
            .addGroup(Panel_ComandosLayout.createSequentialGroup()
                .addContainerGap()
                .addGroup(Panel_ComandosLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addGroup(Panel_ComandosLayout.createSequentialGroup()
                        .addComponent(Titulo_Inicio)
                        .addGap(38, 38, 38)
                        .addComponent(Titulo_Set_Registro)
                        .addGap(11, 11, 11))
                    .addGroup(Panel_ComandosLayout.createSequentialGroup()
                        .addGap(9, 9, 9)
                        .addComponent(Paso)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addGroup(Panel_ComandosLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(Set_Registro)
                            .addComponent(Set_Registro_value))
                        .addGap(44, 44, 44)
                        .addGroup(Panel_ComandosLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(Text_Set_Registro, javax.swing.GroupLayout.PREFERRED_SIZE, 38, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(Text_Set_value, javax.swing.GroupLayout.PREFERRED_SIZE, 49, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addGap(0, 0, Short.MAX_VALUE)))
                .addGap(55, 55, 55))
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, Panel_ComandosLayout.createSequentialGroup()
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addComponent(Volver)
                .addGap(43, 43, 43))
        );
        Panel_ComandosLayout.setVerticalGroup(
            Panel_ComandosLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(Panel_ComandosLayout.createSequentialGroup()
                .addContainerGap()
                .addComponent(Titulo_Comandos)
                .addGap(22, 22, 22)
                .addGroup(Panel_ComandosLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(Titulo_Inicio)
                    .addComponent(Titulo_Set_Registro))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(Panel_ComandosLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(Libre)
                    .addComponent(Text_Set_Registro, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(Set_Registro))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(Panel_ComandosLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(Paso)
                    .addComponent(Text_Set_value, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(Set_Registro_value))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addComponent(Volver)
                .addContainerGap())
        );

        Panel_Desensamble.setBackground(new java.awt.Color(153, 153, 153));

        Titulo_Entradas.setFont(new java.awt.Font("Sylfaen", 1, 17)); // NOI18N
        Titulo_Entradas.setForeground(new java.awt.Color(51, 255, 0));
        Titulo_Entradas.setText("Desensamble");

        TextArea.setColumns(20);
        TextArea.setFont(new java.awt.Font("Sylfaen", 1, 20)); // NOI18N
        TextArea.setRows(5);
        jScrollPane1.setViewportView(TextArea);

        javax.swing.GroupLayout Panel_DesensambleLayout = new javax.swing.GroupLayout(Panel_Desensamble);
        Panel_Desensamble.setLayout(Panel_DesensambleLayout);
        Panel_DesensambleLayout.setHorizontalGroup(
            Panel_DesensambleLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(Panel_DesensambleLayout.createSequentialGroup()
                .addContainerGap()
                .addGroup(Panel_DesensambleLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jScrollPane1)
                    .addGroup(Panel_DesensambleLayout.createSequentialGroup()
                        .addComponent(Titulo_Entradas)
                        .addGap(0, 0, Short.MAX_VALUE)))
                .addContainerGap())
        );
        Panel_DesensambleLayout.setVerticalGroup(
            Panel_DesensambleLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(Panel_DesensambleLayout.createSequentialGroup()
                .addContainerGap()
                .addComponent(Titulo_Entradas)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jScrollPane1, javax.swing.GroupLayout.DEFAULT_SIZE, 378, Short.MAX_VALUE)
                .addContainerGap())
        );

        Panel_Puertos.setBackground(new java.awt.Color(255, 153, 153));

        Titulo_Salidas.setFont(new java.awt.Font("Sylfaen", 1, 15)); // NOI18N
        Titulo_Salidas.setText("Salidas");

        Titulo_Entradas1.setFont(new java.awt.Font("Sylfaen", 1, 15)); // NOI18N
        Titulo_Entradas1.setText("Entradas");

        javax.swing.GroupLayout Panel_PuertosLayout = new javax.swing.GroupLayout(Panel_Puertos);
        Panel_Puertos.setLayout(Panel_PuertosLayout);
        Panel_PuertosLayout.setHorizontalGroup(
            Panel_PuertosLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(Panel_PuertosLayout.createSequentialGroup()
                .addContainerGap()
                .addComponent(Titulo_Salidas)
                .addContainerGap(45, Short.MAX_VALUE))
            .addGroup(Panel_PuertosLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, Panel_PuertosLayout.createSequentialGroup()
                    .addContainerGap(22, Short.MAX_VALUE)
                    .addComponent(Titulo_Entradas1)
                    .addGap(19, 19, 19)))
        );
        Panel_PuertosLayout.setVerticalGroup(
            Panel_PuertosLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(Panel_PuertosLayout.createSequentialGroup()
                .addGap(368, 368, 368)
                .addComponent(Titulo_Salidas)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
            .addGroup(Panel_PuertosLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                .addGroup(Panel_PuertosLayout.createSequentialGroup()
                    .addGap(23, 23, 23)
                    .addComponent(Titulo_Entradas1)
                    .addContainerGap(732, Short.MAX_VALUE)))
        );

        Panel_Pila.setBackground(new java.awt.Color(153, 255, 153));

        Titulo_Pila.setFont(new java.awt.Font("Sylfaen", 1, 15)); // NOI18N
        Titulo_Pila.setText("Pila");

        NumerosPila.setBackground(new java.awt.Color(102, 255, 102));
        jScrollPane3.setViewportView(NumerosPila);

        javax.swing.GroupLayout Panel_PilaLayout = new javax.swing.GroupLayout(Panel_Pila);
        Panel_Pila.setLayout(Panel_PilaLayout);
        Panel_PilaLayout.setHorizontalGroup(
            Panel_PilaLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(Panel_PilaLayout.createSequentialGroup()
                .addContainerGap()
                .addComponent(Titulo_Pila)
                .addContainerGap(26, Short.MAX_VALUE))
            .addComponent(jScrollPane3, javax.swing.GroupLayout.Alignment.TRAILING)
        );
        Panel_PilaLayout.setVerticalGroup(
            Panel_PilaLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(Panel_PilaLayout.createSequentialGroup()
                .addContainerGap()
                .addComponent(Titulo_Pila)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jScrollPane3)
                .addContainerGap())
        );

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(0, 0, 0)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addGroup(layout.createSequentialGroup()
                        .addComponent(Panel_Registros, javax.swing.GroupLayout.PREFERRED_SIZE, 444, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(Panel_Comandos, javax.swing.GroupLayout.PREFERRED_SIZE, 384, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addComponent(Panel_Desensamble, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(Panel_Puertos, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(Panel_Pila, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap())
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING, false)
                            .addComponent(Panel_Comandos, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                            .addComponent(Panel_Registros, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(Panel_Desensamble, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                    .addComponent(Panel_Puertos, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(Panel_Pila, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                .addContainerGap())
        );

        pack();
    }// </editor-fold>                        

    private void Button_Volver(java.awt.event.MouseEvent evt) {                               
        this.setVisible(false);
    }                              

    private void Button_Libre(java.awt.event.MouseEvent evt) {                              
        //Registros
        HashMap <String,Integer> registros = new HashMap<String,Integer>();
        registros.put("A", 0);
        registros.put("B", 0);
        registros.put("C", 0);
        registros.put("D", 0);
        registros.put("E", 0);
        registros.put("F", 0);
        registros.put("H", 0);
        registros.put("L", 0);
        registros.put("A_1", 0);
        registros.put("B_1", 0);
        registros.put("C_1", 0);
        registros.put("D_1", 0);
        registros.put("F_1", 0);
        registros.put("H_1", 0);
        registros.put("L_1", 0);
        registros.put("PC_1", 0);
        registros.put("SF_value", 0);
        registros.put("ZF_value", 0);
        registros.put("HF_value", 0);
        registros.put("PF_value", 0);
        registros.put("NF_value", 0);
        registros.put("CF_value", 0);
        
        String mensaje = "";
        System.out.println(comandos.size());
        Integer resultado;
        
        //CICLO
        for(int i=0; i<comandos.size();i++){
            System.out.println(comandos.get(i).instruccion);
            
            //FUNCIONES 2 ENTRADAS
            
            if(comandos.get(i).B != null){
                mensaje = mensaje + comandos.get(i).instruccion+"   ->   "+comandos.get(i).A+"  ,  "+comandos.get(i).B+"\n";
                
                switch(comandos.get(i).instruccion){
                    case "LD":
                        resultado = this.LD(registros.get(comandos.get(i).A), registros.get(comandos.get(i).B));
                        //Resultado es donde se guarda el valor a modificar
                        // resultado = this.<FUNCION>(<ENTRADA "A">,<ENTRADA "B">);
                        //ENTRADA 1 >>>>>>>    registros.get(comandos.get(i).A)
                        //ENTRADA 2 >>>>>>     registros.get(comandos.get(i).B)
                        
                        //MODIFICAR LOS REGISTROS
                        //MODIFICAR HASHMAP
                        registros.replace(comandos.get(i).A, resultado);
                        //registros.replace(<REGISTRO EN DONDE SE GUARDA> , <RESULTADO>);
                        //comandos es una lista de 1 hasta i comandos registrados
                        
                        //MODIFICAN LAS BANDERAS
                        //Z
                        if(resultado < 0){
                            registros.replace("ZF_value", 1);
                        }else{
                            registros.replace("ZF_value", 0);
                        }
                        
                        
                        
                        //MODIFICAR INTERFAZ
                        this.A_value.setText(String.valueOf(resultado));
                        break;
                        
 
                    default:
                        break;
                }
            }
            //FUNCIONES 1 ENTRADAS
            else{
                mensaje = mensaje + comandos.get(i).instruccion+"   ->   "+comandos.get(i).A+"\n";
                
                switch(comandos.get(i).instruccion){
                    case "ADD":
                        resultado = this.ADD(registros.get(comandos.get(i).A));
                        //ENTRADA >>>>>>>> registros.get(comandos.get(i).A)
                        registros.replace(comandos.get(i).A, resultado);
                        this.A_value.setText(String.valueOf(resultado));
                        break;
                    case "DEC":
                        resultado = this.DEC(registros.get(comandos.get(i).A));
                        //ENTRADA >>>>>>>> registros.get(comandos.get(i).A)
                        registros.replace(comandos.get(i).A, resultado);
                        this.A_value.setText(String.valueOf(resultado));
                        break;
                    case "CP":
                        resultado = this.CP(registros.get(comandos.get(i).A), registros.get("A"));
                        if(resultado <= 0){
                            registros.replace("ZF_value", 1);
                        }
                        break;
                    case "PUSH":
                        this.PUSH(comandos.get(i).A);
                    default:
                        break;
                }
            }
        }
        
        System.out.println(mensaje);
        TextArea.setText(mensaje);
    }                             

    private void Button_Paso(java.awt.event.MouseEvent evt) {                             
        // TODO add your handling code here:
    }                            

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(Ejecucion.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(Ejecucion.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(Ejecucion.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(Ejecucion.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new Ejecucion().setVisible(true);
            }
        });
    }

    ///////////////////////////////////////////////////////////////////////////////////////////////////////////////////////////////////////////////////////////////////////////////////
    //Instrucciones 
    //" Entradas
    public static int LD (int A, int B){
        int resultado = A + B;
        return resultado;
    }
    
    
    

    
    
    
    
    
    //1 Entrada
    public static int ADD (int A){
        return A+1;
    }
    public static int DEC (int A){
        return A-1;
    }
    
    public static int CP(int A,int B){
        return B-A;
    }
    
        public void PUSH(String A){
        switch(A){
            case "IX":
                NumerosPila.setText(IX_value.getText());
                break;
            case "IY":
                NumerosPila.setText(IY_value.getText());
                break;
            case "BC":
                NumerosPila.setText(B_value.getText().concat(C_value.getText()));
                break;
            case "DE":
                NumerosPila.setText(D_value.getText().concat(E_value.getText()));
                break;
            case "HL":
                NumerosPila.setText(H_value.getText().concat(L_value.getText()));
                break;
            case "AF":
                NumerosPila.setText(A_value.getText().concat(F_value.getText()));
                break;
        }
    }
    //////////////////////////////////////////////////////////////////////////////////////////////////////////////////////////////////////////////////////////////////////////////////
    // Variables declaration - do not modify                     
    private javax.swing.JLabel A;
    private javax.swing.JLabel A1;
    private javax.swing.JLabel A_value;
    private javax.swing.JLabel A_value1;
    private javax.swing.JLabel B;
    private javax.swing.JLabel B1;
    private javax.swing.JLabel B_value;
    private javax.swing.JLabel B_value1;
    private javax.swing.JLabel C;
    private javax.swing.JLabel C1;
    private javax.swing.JLabel CF_value;
    private javax.swing.JLabel C_F;
    private javax.swing.JLabel C_value;
    private javax.swing.JLabel C_value1;
    private javax.swing.JLabel D;
    private javax.swing.JLabel D1;
    private javax.swing.JLabel D_value;
    private javax.swing.JLabel D_value1;
    private javax.swing.JLabel E;
    private javax.swing.JLabel E1;
    private javax.swing.JLabel E_value;
    private javax.swing.JLabel E_value1;
    private javax.swing.JLabel F;
    private javax.swing.JLabel F1;
    private javax.swing.JLabel FLAGS;
    private javax.swing.JLabel F_value;
    private javax.swing.JLabel F_value1;
    private javax.swing.JLabel H;
    private javax.swing.JLabel H1;
    private javax.swing.JLabel HF_value;
    private javax.swing.JLabel H_F;
    private javax.swing.JLabel H_value;
    private javax.swing.JLabel H_value1;
    private javax.swing.JLabel I;
    private javax.swing.JLabel IX;
    private javax.swing.JLabel IX_value;
    private javax.swing.JLabel IY;
    private javax.swing.JLabel IY_value;
    private javax.swing.JLabel I_value;
    private javax.swing.JLabel L;
    private javax.swing.JLabel L1;
    private javax.swing.JLabel L_value;
    private javax.swing.JLabel L_value1;
    private javax.swing.JButton Libre;
    private javax.swing.JLabel NF_value;
    private javax.swing.JLabel N_F;
    private javax.swing.JTextPane NumerosPila;
    private javax.swing.JLabel PC;
    private javax.swing.JLabel PC_value;
    private javax.swing.JLabel PF_value;
    private javax.swing.JLabel P_F;
    private javax.swing.JPanel Panel_Comandos;
    private javax.swing.JPanel Panel_Desensamble;
    private javax.swing.JPanel Panel_Pila;
    private javax.swing.JPanel Panel_Puertos;
    private javax.swing.JPanel Panel_Registros;
    private javax.swing.JButton Paso;
    private javax.swing.JLabel Quinto_0;
    private javax.swing.JLabel R;
    private javax.swing.JLabel R_value;
    private javax.swing.JLabel SF_value;
    private javax.swing.JLabel SP;
    private javax.swing.JLabel SP_value;
    private javax.swing.JLabel S_F;
    private javax.swing.JLabel Set_Registro;
    private javax.swing.JLabel Set_Registro_value;
    private javax.swing.JLabel Tercer_0;
    private javax.swing.JTextArea TextArea;
    private javax.swing.JTextField Text_Set_Registro;
    private javax.swing.JTextField Text_Set_value;
    private javax.swing.JLabel Titulo_Comandos;
    private javax.swing.JLabel Titulo_Entradas;
    private javax.swing.JLabel Titulo_Entradas1;
    private javax.swing.JLabel Titulo_Inicio;
    private javax.swing.JLabel Titulo_Pila;
    private javax.swing.JLabel Titulo_Registros;
    private javax.swing.JLabel Titulo_Salidas;
    private javax.swing.JLabel Titulo_Set_Registro;
    private javax.swing.JButton Volver;
    private javax.swing.JLabel ZF_value;
    private javax.swing.JLabel Z_F;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JScrollPane jScrollPane2;
    private javax.swing.JScrollPane jScrollPane3;
    private javax.swing.JTextArea jTextArea1;
    // End of variables declaration                   
}
